.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH autocrypt 1 "July 2022" "sq 0.26.0" "Sequoia Manual"
.SH NAME
autocrypt \- Communicates certificates using Autocrypt
.SH SYNOPSIS
\fBautocrypt\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Communicates certificates using Autocrypt
.PP
Autocrypt is a standard for mail user agents to provide convenient
end\-to\-end encryption of emails.  This subcommand provides a limited
way to produce and consume headers that are used by Autocrypt to
communicate certificates between clients.
.PP
See https://autocrypt.org/
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.SH SUBCOMMANDS
.TP
autocrypt\-decode(1)
Reads Autocrypt\-encoded certificates
.TP
autocrypt\-encode\-sender(1)
Encodes a certificate into an Autocrypt header
.SH "SEE ALSO"
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.
.PP
sq(1)
sq\-armor(1)
sq\-autocrypt\-decode(1)
sq\-autocrypt\-encode\-sender(1)
sq\-certify(1)
sq\-dearmor(1)
sq\-decrypt(1)
sq\-encrypt(1)
sq\-inspect(1)
sq\-key(1)
sq\-keyring(1)
sq\-keyserver(1)
sq\-packet(1)
sq\-revoke(1)
sq\-sign(1)
sq\-verify(1)
sq\-wkd(1)
