.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH encode-sender 1 "July 2022" "sq 0.26.0" "Sequoia Manual"
.SH NAME
encode\-sender \- Encodes a certificate into an Autocrypt header
.SH SYNOPSIS
\fBencode\-sender\fR [\fB\-o\fR|\fB\-\-output\fR] [\fB\-\-email\fR] [\fB\-\-prefer\-encrypt\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIFILE\fR] 
.SH DESCRIPTION
Encodes a certificate into an Autocrypt header
.PP
A certificate can be encoded and included in a header of an email
message.  This command encodes the certificate, adds the senders email
address (which must match the one used in the "From" header), and the
senders "prefer\-encrypt" state (see the Autocrypt spec for more
information).
.PP
The converse operation is "sq autocrypt decode".
.SH OPTIONS
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Writes to FILE or stdout if omitted
.TP
\fB\-\-email\fR=\fIADDRESS\fR
Sets the address [default: primary userid]
.TP
\fB\-\-prefer\-encrypt\fR=\fIPREFER\-ENCRYPT\fR [default: nopreference] [possible values: nopreference, mutual]
Sets the prefer\-encrypt attribute
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
[\fIFILE\fR]
Reads from FILE or stdin if omitted
.SH EXAMPLES
 Encodes a certificate
.PP
.nf
.RS
 sq autocrypt encode\-sender juliet.pgp
.RE
.fi
.PP
 Encodes a certificate with an explicit sender address
.PP
.nf
.RS
 sq autocrypt encode\-sender \-\-email juliet@example.org juliet.pgp
.RE
.fi
.PP
 Encodes a certificate while indicating the willingness to encrypt
.PP
.nf
.RS
 sq autocrypt encode\-sender \-\-prefer\-encrypt mutual juliet.pgp
.RE
.fi
.SH "SEE ALSO"
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.
.PP
sq(1)
sq\-armor(1)
sq\-autocrypt(1)
sq\-autocrypt\-decode(1)
sq\-certify(1)
sq\-dearmor(1)
sq\-decrypt(1)
sq\-encrypt(1)
sq\-inspect(1)
sq\-key(1)
sq\-keyring(1)
sq\-keyserver(1)
sq\-packet(1)
sq\-revoke(1)
sq\-sign(1)
sq\-verify(1)
sq\-wkd(1)
