.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH armor 1 "July 2022" "sq 0.26.0" "Sequoia Manual"
.SH NAME
armor \- Converts binary to ASCII
.SH SYNOPSIS
\fBarmor\fR [\fB\-o\fR|\fB\-\-output\fR] [\fB\-\-label\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIFILE\fR] 
.SH DESCRIPTION
Converts binary to ASCII
.PP
To make encrypted data easier to handle and transport, OpenPGP data
can be transformed to an ASCII representation called ASCII Armor.  sq
emits armored data by default, but this subcommand can be used to
convert existing OpenPGP data to its ASCII\-encoded representation.
.PP
The converse operation is "sq dearmor".
.SH OPTIONS
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Writes to FILE or stdout if omitted
.TP
\fB\-\-label\fR=\fILABEL\fR [default: auto] [possible values: auto, message, cert, key, sig, file]
Selects the kind of armor header
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
[\fIFILE\fR]
Reads from FILE or stdin if omitted
.SH EXAMPLES
 Convert a binary certificate to ASCII
.PP
.nf
.RS
 sq armor binary\-juliet.pgp
.RE
.fi
.PP
 Convert a binary message to ASCII
.PP
.nf
.RS
 sq armor binary\-message.pgp
.RE
.fi
.SH "SEE ALSO"
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.
.PP
sq(1)
sq\-certify(1)
sq\-dearmor(1)
sq\-decrypt(1)
sq\-encrypt(1)
sq\-inspect(1)
sq\-key(1)
sq\-keyring(1)
sq\-keyserver(1)
sq\-packet(1)
sq\-revoke(1)
sq\-sign(1)
sq\-verify(1)
sq\-wkd(1)
