.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH join 1 "July 2022" "sq 0.26.0" "Sequoia Manual"
.SH NAME
join \- Joins keys or keyrings into a single keyring
.SH SYNOPSIS
\fBjoin\fR [\fB\-o\fR|\fB\-\-output\fR] [\fB\-B\fR|\fB\-\-binary\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIFILE\fR] 
.SH DESCRIPTION
Joins keys or keyrings into a single keyring
.PP
Unlike "sq keyring merge", multiple versions of the same key are not
merged together.
.PP
The converse operation is "sq keyring split".
.SH OPTIONS
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Sets the output file to use
.TP
\fB\-B\fR, \fB\-\-binary\fR
Don\*(Aqt ASCII\-armor the keyring
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
[\fIFILE\fR]
Sets the input files to use
.SH EXAMPLES
 Collect certs for an email conversation
.PP
.nf
.RS
 sq keyring join juliet.pgp romeo.pgp alice.pgp
.RE
.fi
.SH "SEE ALSO"
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.
.PP
sq(1)
sq\-armor(1)
sq\-certify(1)
sq\-dearmor(1)
sq\-decrypt(1)
sq\-encrypt(1)
sq\-inspect(1)
sq\-key(1)
sq\-keyring(1)
sq\-keyring\-filter(1)
sq\-keyring\-list(1)
sq\-keyring\-merge(1)
sq\-keyring\-split(1)
sq\-keyserver(1)
sq\-packet(1)
sq\-revoke(1)
sq\-sign(1)
sq\-verify(1)
sq\-wkd(1)
