.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH packet 1 "July 2022" "sq 0.26.0" "Sequoia Manual"
.SH NAME
packet \- Low\-level packet manipulation
.SH SYNOPSIS
\fBpacket\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Low\-level packet manipulation
.PP
An OpenPGP data stream consists of packets.  These tools allow working
with packet streams.  They are mostly of interest to developers, but
"sq packet dump" may be helpful to a wider audience both to provide
valuable information in bug reports to OpenPGP\-related software, and
as a learning tool.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.SH SUBCOMMANDS
.TP
packet\-dump(1)
Lists packets
.TP
packet\-decrypt(1)
Unwraps an encryption container
.TP
packet\-split(1)
Splits a message into packets
.TP
packet\-join(1)
Joins packets split across files
.SH "SEE ALSO"
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.
.PP
sq(1)
sq\-armor(1)
sq\-certify(1)
sq\-dearmor(1)
sq\-decrypt(1)
sq\-encrypt(1)
sq\-inspect(1)
sq\-key(1)
sq\-keyring(1)
sq\-keyserver(1)
sq\-packet\-decrypt(1)
sq\-packet\-dump(1)
sq\-packet\-join(1)
sq\-packet\-split(1)
sq\-revoke(1)
sq\-sign(1)
sq\-verify(1)
sq\-wkd(1)
