.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH split 1 "July 2022" "sq 0.26.0" "Sequoia Manual"
.SH NAME
split \- Splits a message into packets
.SH SYNOPSIS
\fBsplit\fR [\fB\-p\fR|\fB\-\-prefix\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIFILE\fR] 
.SH DESCRIPTION
Splits a message into packets
.PP
Splitting a packet sequence into individual packets, then recombining
them freely with "sq packet join" is a great way to experiment with
OpenPGP data.
.PP
The converse operation is "sq packet join".
.SH OPTIONS
.TP
\fB\-p\fR, \fB\-\-prefix\fR=\fIPREFIX\fR
Writes to files with PREFIX [defaults: "FILE\-" if FILE is set, or "output\-" if read from stdin]
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
[\fIFILE\fR]
Reads from FILE or stdin if omitted
.SH EXAMPLES
 Split a certificate into individual packets
.PP
.nf
.RS
 sq packet split juliet.pgp
.RE
.fi
.SH "SEE ALSO"
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.
.PP
sq(1)
sq\-armor(1)
sq\-certify(1)
sq\-dearmor(1)
sq\-decrypt(1)
sq\-encrypt(1)
sq\-inspect(1)
sq\-key(1)
sq\-keyring(1)
sq\-keyserver(1)
sq\-packet(1)
sq\-packet\-decrypt(1)
sq\-packet\-dump(1)
sq\-packet\-join(1)
sq\-revoke(1)
sq\-sign(1)
sq\-verify(1)
sq\-wkd(1)
