.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH direct-url 1 "July 2022" "sq 0.26.0" "Sequoia Manual"
.SH NAME
direct\-url \- Prints the direct Web Key Directory URL of an email address.
.SH SYNOPSIS
\fBdirect\-url\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIADDRESS\fR> 
.SH DESCRIPTION
Prints the direct Web Key Directory URL of an email address.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
<\fIADDRESS\fR>
Queries for ADDRESS
.SH "SEE ALSO"
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.
.PP
sq(1)
sq\-armor(1)
sq\-certify(1)
sq\-dearmor(1)
sq\-decrypt(1)
sq\-encrypt(1)
sq\-inspect(1)
sq\-key(1)
sq\-keyring(1)
sq\-keyserver(1)
sq\-packet(1)
sq\-revoke(1)
sq\-sign(1)
sq\-verify(1)
sq\-wkd(1)
sq\-wkd\-generate(1)
sq\-wkd\-get(1)
sq\-wkd\-url(1)
