.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH sq 1 "July 2022" "sq 0.26.0" "Sequoia Manual"
.SH NAME
sq \- A command\-line frontend for Sequoia, an implementation of OpenPGP
.SH SYNOPSIS
\fBsq\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fB\-f\fR|\fB\-\-force\fR] [\fB\-\-known\-notation\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
A command\-line frontend for Sequoia, an implementation of OpenPGP
.PP
Functionality is grouped and available using subcommands.  Currently,
this interface is completely stateless.  Therefore, you need to supply
all configuration and certificates explicitly on each invocation.
.PP
OpenPGP data can be provided in binary or ASCII armored form.  This
will be handled automatically.  Emitted OpenPGP data is ASCII armored
by default.
.PP
We use the term "certificate", or cert for short, to refer to OpenPGP
keys that do not contain secrets.  Conversely, we use the term "key"
to refer to OpenPGP keys that do contain secrets.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information
.TP
\fB\-f\fR, \fB\-\-force\fR
Overwrites existing files
.TP
\fB\-\-known\-notation\fR=\fINOTATION\fR
Adds NOTATION to the list of known notations. This is used when validating signatures. Signatures that have unknown notations with the critical bit set are considered invalid.
.SH SUBCOMMANDS
.TP
sq\-armor(1)
Converts binary to ASCII
.TP
sq\-dearmor(1)
Converts ASCII to binary
.TP
sq\-sign(1)
Signs messages or data files
.TP
sq\-verify(1)
Verifies signed messages or detached signatures
.TP
sq\-wkd(1)
Interacts with Web Key Directories
.TP
sq\-keyserver(1)
Interacts with keyservers
.TP
sq\-revoke(1)
Generates revocation certificates
.TP
sq\-packet(1)
Low\-level packet manipulation
.TP
sq\-certify(1)
Certifies a User ID for a Certificate
.TP
sq\-keyring(1)
Manages collections of keys or certs
.TP
sq\-key(1)
Manages keys
.TP
sq\-inspect(1)
Inspects data, like file(1)
.TP
sq\-encrypt(1)
Encrypts a message
.TP
sq\-decrypt(1)
Decrypts a message
.SH "SEE ALSO"
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.
.PP
sq\-armor(1)
sq\-certify(1)
sq\-dearmor(1)
sq\-decrypt(1)
sq\-encrypt(1)
sq\-inspect(1)
sq\-key(1)
sq\-keyring(1)
sq\-keyserver(1)
sq\-packet(1)
sq\-revoke(1)
sq\-sign(1)
sq\-verify(1)
sq\-wkd(1)
.SH VERSION
v0.26.0 (sequoia\-openpgp 1.10.0, using Nettle)
