.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dearmor 1 "July 2022" "sq 0.26.0" "Sequoia Manual"
.SH NAME
dearmor \- Converts ASCII to binary
.SH SYNOPSIS
\fBdearmor\fR [\fB\-o\fR|\fB\-\-output\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIFILE\fR] 
.SH DESCRIPTION
Converts ASCII to binary
.PP
To make encrypted data easier to handle and transport, OpenPGP data
can be transformed to an ASCII representation called ASCII Armor.  sq
transparently handles armored data, but this subcommand can be used to
explicitly convert existing ASCII\-encoded OpenPGP data to its binary
representation.
.PP
The converse operation is "sq armor".
.SH OPTIONS
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Writes to FILE or stdout if omitted
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
[\fIFILE\fR]
Reads from FILE or stdin if omitted
.SH EXAMPLES
 Convert a ASCII certificate to binary
.PP
.nf
.RS
 sq dearmor ascii\-juliet.pgp
.RE
.fi
.PP
 Convert a ASCII message to binary
.PP
.nf
.RS
 sq dearmor ascii\-message.pgp
.RE
.fi
.SH "SEE ALSO"
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.
.PP
sq(1)
sq\-armor(1)
sq\-autocrypt(1)
sq\-certify(1)
sq\-decrypt(1)
sq\-encrypt(1)
sq\-inspect(1)
sq\-key(1)
sq\-keyring(1)
sq\-keyserver(1)
sq\-packet(1)
sq\-revoke(1)
sq\-sign(1)
sq\-verify(1)
sq\-wkd(1)
