.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH decrypt 1 "July 2022" "sq 0.26.0" "Sequoia Manual"
.SH NAME
decrypt \- Decrypts a message
.SH SYNOPSIS
\fBdecrypt\fR [\fB\-o\fR|\fB\-\-output\fR] [\fB\-n\fR|\fB\-\-signatures\fR] [\fB\-\-signer\-cert\fR] [\fB\-\-recipient\-key\fR] [\fB\-\-private\-key\-store\fR] [\fB\-\-dump\-session\-key\fR] [\fB\-\-session\-key\fR] [\fB\-\-dump\fR] [\fB\-x\fR|\fB\-\-hex\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIFILE\fR] 
.SH DESCRIPTION
Decrypts a message
.PP
Decrypts a message using either supplied keys, or by prompting for a
password.  If message tampering is detected, an error is returned.
See below for details.
.PP
If certificates are supplied using the "\-\-signer\-cert" option, any
signatures that are found are checked using these certificates.
Verification is only successful if there is no bad signature, and the
number of successfully verified signatures reaches the threshold
configured with the "\-\-signatures" parameter.
.PP
If the signature verification fails, or if message tampering is
detected, the program terminates with an exit status indicating
failure.  In addition to that, the last 25 MiB of the message are
withheld, i.e. if the message is smaller than 25 MiB, no output is
produced, and if it is larger, then the output will be truncated.
.PP
The converse operation is "sq encrypt".
.SH OPTIONS
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Writes to FILE or stdout if omitted
.TP
\fB\-n\fR, \fB\-\-signatures\fR=\fIN\fR
Sets the threshold of valid signatures to N. The message will only be considered verified if this threshold is reached. [default: 1 if at least one signer cert file is given, 0 otherwise]
.TP
\fB\-\-signer\-cert\fR=\fICERT\fR
Verifies signatures with CERT
.TP
\fB\-\-recipient\-key\fR=\fIKEY\fR
Decrypts with KEY
.TP
\fB\-\-private\-key\-store\fR=\fIKEY_STORE\fR
Provides parameters for private key store
.TP
\fB\-\-dump\-session\-key\fR
Prints the session key to stderr
.TP
\fB\-\-session\-key\fR=\fISESSION\-KEY\fR
Decrypts an encrypted message using SESSION\-KEY
.TP
\fB\-\-dump\fR
Prints a packet dump to stderr
.TP
\fB\-x\fR, \fB\-\-hex\fR
Prints a hexdump (implies \-\-dump)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
[\fIFILE\fR]
Reads from FILE or stdin if omitted
.SH EXAMPLES
 Decrypt a file using a secret key
.PP
.nf
.RS
 sq decrypt \-\-recipient\-key juliet.pgp ciphertext.pgp
.RE
.fi
.PP
 Decrypt a file verifying signatures
.PP
.nf
.RS
 sq decrypt \-\-recipient\-key juliet.pgp \-\-signer\-cert romeo.pgp ciphertext.pgp
.RE
.fi
.PP
 Decrypt a file using a password
.PP
.nf
.RS
 sq decrypt ciphertext.pgp
.RE
.fi
.SH "SEE ALSO"
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.
.PP
sq(1)
sq\-armor(1)
sq\-autocrypt(1)
sq\-certify(1)
sq\-dearmor(1)
sq\-encrypt(1)
sq\-inspect(1)
sq\-key(1)
sq\-keyring(1)
sq\-keyserver(1)
sq\-packet(1)
sq\-revoke(1)
sq\-sign(1)
sq\-verify(1)
sq\-wkd(1)
