.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH keyring 1 "July 2022" "sq 0.26.0" "Sequoia Manual"
.SH NAME
keyring \- Manages collections of keys or certs
.SH SYNOPSIS
\fBkeyring\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Manages collections of keys or certs
.PP
Collections of keys or certficicates (also known as "keyrings" when
they contain secret key material, and "certrings" when they don\*(Aqt) are
any number of concatenated certificates.  This subcommand provides
tools to list, split, join, merge, and filter keyrings.
.PP
Note: In the documentation of this subcommand, we sometimes use the
terms keys and certs interchangeably.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.SH SUBCOMMANDS
.TP
keyring\-filter(1)
Joins keys into a keyring applying a filter
.TP
keyring\-join(1)
Joins keys or keyrings into a single keyring
.TP
keyring\-merge(1)
Merges keys or keyrings into a single keyring
.TP
keyring\-list(1)
Lists keys in a keyring
.TP
keyring\-split(1)
Splits a keyring into individual keys
.SH "SEE ALSO"
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.
.PP
sq(1)
sq\-armor(1)
sq\-autocrypt(1)
sq\-certify(1)
sq\-dearmor(1)
sq\-decrypt(1)
sq\-encrypt(1)
sq\-inspect(1)
sq\-key(1)
sq\-keyring\-filter(1)
sq\-keyring\-join(1)
sq\-keyring\-list(1)
sq\-keyring\-merge(1)
sq\-keyring\-split(1)
sq\-keyserver(1)
sq\-packet(1)
sq\-revoke(1)
sq\-sign(1)
sq\-verify(1)
sq\-wkd(1)
