.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH adopt 1 "July 2022" "sq 0.26.0" "Sequoia Manual"
.SH NAME
adopt \- Binds keys from one certificate to another
.SH SYNOPSIS
\fBadopt\fR [\fB\-r\fR|\fB\-\-keyring\fR] <\fB\-k\fR|\fB\-\-key\fR> [\fB\-\-allow\-broken\-crypto\fR] [\fB\-o\fR|\fB\-\-output\fR] [\fB\-B\fR|\fB\-\-binary\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fITARGET\-KEY\fR] 
.SH DESCRIPTION
Binds keys from one certificate to another
.PP
This command allows one to transfer primary keys and subkeys into an
existing certificate.  Say you want to transition to a new
certificate, but have an authentication subkey on your current
certificate.  You want to keep the authentication subkey because it
allows access to SSH servers and updating their configuration is not
feasible.
.SH OPTIONS
.TP
\fB\-r\fR, \fB\-\-keyring\fR=\fIKEY\-RING\fR
Supplies keys for use in \-\-key.
.TP
\fB\-k\fR, \fB\-\-key\fR=\fIKEY\fR
Adds the key or subkey KEY to the TARGET\-KEY
.TP
\fB\-\-allow\-broken\-crypto\fR
Allows adopting keys from certificates using broken cryptography
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Writes to FILE or stdout if omitted
.TP
\fB\-B\fR, \fB\-\-binary\fR
Emits binary data
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
[\fITARGET\-KEY\fR]
Adds keys to TARGET\-KEY
.SH EXAMPLES
 Adopt an subkey into the new cert
.PP
.nf
.RS
 sq key adopt \-\-keyring juliet\-old.pgp \-\-key 0123456789ABCDEF \-\- juliet\-new.pgp
.RE
.fi
.SH "SEE ALSO"
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.
.PP
sq(1)
sq\-armor(1)
sq\-autocrypt(1)
sq\-certify(1)
sq\-dearmor(1)
sq\-decrypt(1)
sq\-encrypt(1)
sq\-inspect(1)
sq\-key(1)
sq\-key\-attest\-certifications(1)
sq\-key\-extract\-cert(1)
sq\-key\-generate(1)
sq\-key\-password(1)
sq\-key\-userid(1)
sq\-keyring(1)
sq\-keyserver(1)
sq\-packet(1)
sq\-revoke(1)
sq\-sign(1)
sq\-verify(1)
sq\-wkd(1)
