.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH list 1 "July 2022" "sq 0.26.0" "Sequoia Manual"
.SH NAME
list \- Lists keys in a keyring
.SH SYNOPSIS
\fBlist\fR [\fB\-\-all\-userids\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIFILE\fR] 
.SH DESCRIPTION
Lists keys in a keyring
.PP
Prints the fingerprint as well as the primary userid for every
certificate encountered in the keyring.
.SH OPTIONS
.TP
\fB\-\-all\-userids\fR
Lists all user ids, even those that are expired, revoked, or not valid under the standard policy.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
[\fIFILE\fR]
Reads from FILE or stdin if omitted
.SH EXAMPLES
 List all certs
.PP
.nf
.RS
 sq keyring list certs.pgp
.RE
.fi
.PP
 List all certs with a userid on example.org
.PP
.nf
.RS
 sq keyring filter \-\-domain example.org certs.pgp | sq keyring list
.RE
.fi
.SH "SEE ALSO"
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.
.PP
sq(1)
sq\-armor(1)
sq\-autocrypt(1)
sq\-certify(1)
sq\-dearmor(1)
sq\-decrypt(1)
sq\-encrypt(1)
sq\-inspect(1)
sq\-key(1)
sq\-keyring(1)
sq\-keyring\-filter(1)
sq\-keyring\-join(1)
sq\-keyring\-merge(1)
sq\-keyring\-split(1)
sq\-keyserver(1)
sq\-packet(1)
sq\-revoke(1)
sq\-sign(1)
sq\-verify(1)
sq\-wkd(1)
