.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH attest-certifications 1 "July 2022" "sq 0.26.0" "Sequoia Manual"
.SH NAME
attest\-certifications \- Attests to third\-party certifications
.SH SYNOPSIS
\fBattest\-certifications\fR [\fB\-\-none\fR] [\fB\-\-all\fR] [\fB\-o\fR|\fB\-\-output\fR] [\fB\-B\fR|\fB\-\-binary\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIKEY\fR] 
.SH DESCRIPTION
.PP
Attests to third\-party certifications allowing for their distribution
.PP
To prevent certificate flooding attacks, modern key servers prevent
uncontrolled distribution of third\-party certifications on
certificates.  To make the key holder the sovereign over the
information over what information is distributed with the certificate,
the key holder needs to explicitly attest to third\-party
certifications.
.PP
After the attestation has been created, the certificate has to be
distributed, e.g. by uploading it to a keyserver.
.SH OPTIONS
.TP
\fB\-\-none\fR
Removes all prior attestations
.TP
\fB\-\-all\fR
Attests to all certifications [default]
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Writes to FILE or stdout if omitted
.TP
\fB\-B\fR, \fB\-\-binary\fR
Emits binary data
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
[\fIKEY\fR]
Changes attestations on KEY
.SH EXAMPLES
 Attest to all certifications present on the key
.PP
.nf
.RS
 sq key attest\-certifications juliet.pgp
.RE
.fi
.PP
 Retract prior attestations on the key
.PP
.nf
.RS
 sq key attest\-certifications \-\-none juliet.pgp
.RE
.fi
.SH "SEE ALSO"
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.
.PP
sq(1)
sq\-armor(1)
sq\-autocrypt(1)
sq\-certify(1)
sq\-dearmor(1)
sq\-decrypt(1)
sq\-encrypt(1)
sq\-inspect(1)
sq\-key(1)
sq\-key\-adopt(1)
sq\-key\-extract\-cert(1)
sq\-key\-generate(1)
sq\-key\-password(1)
sq\-key\-userid(1)
sq\-keyring(1)
sq\-keyserver(1)
sq\-packet(1)
sq\-revoke(1)
sq\-sign(1)
sq\-verify(1)
sq\-wkd(1)
