.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH merge 1 "July 2022" "sq 0.26.0" "Sequoia Manual"
.SH NAME
merge \- Merges keys or keyrings into a single keyring
.SH SYNOPSIS
\fBmerge\fR [\fB\-o\fR|\fB\-\-output\fR] [\fB\-B\fR|\fB\-\-binary\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIFILE\fR] 
.SH DESCRIPTION
Merges keys or keyrings into a single keyring
.PP
Unlike "sq keyring join", the certificates are buffered and multiple
versions of the same certificate are merged together.  Where data is
replaced (e.g., secret key material), data from the later certificate
is preferred.
.SH OPTIONS
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Writes to FILE or stdout if omitted
.TP
\fB\-B\fR, \fB\-\-binary\fR
Emits binary data
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
[\fIFILE\fR]
Reads from FILE
.SH EXAMPLES
 Merge certificate updates
.PP
.nf
.RS
 sq keyring merge certs.pgp romeo\-updates.pgp
.RE
.fi
.SH "SEE ALSO"
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.
.PP
sq(1)
sq\-armor(1)
sq\-autocrypt(1)
sq\-certify(1)
sq\-dearmor(1)
sq\-decrypt(1)
sq\-encrypt(1)
sq\-inspect(1)
sq\-key(1)
sq\-keyring(1)
sq\-keyring\-filter(1)
sq\-keyring\-join(1)
sq\-keyring\-list(1)
sq\-keyring\-split(1)
sq\-keyserver(1)
sq\-packet(1)
sq\-revoke(1)
sq\-sign(1)
sq\-verify(1)
sq\-wkd(1)
