.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH key 1 "July 2022" "sq 0.26.0" "Sequoia Manual"
.SH NAME
key \- Manages keys
.SH SYNOPSIS
\fBkey\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Manages keys
.PP
We use the term "key" to refer to OpenPGP keys that do contain
secrets.  This subcommand provides primitives to generate and
otherwise manipulate keys.
.PP
Conversely, we use the term "certificate", or cert for short, to refer
to OpenPGP keys that do not contain secrets.  See "sq keyring" for
operations on certificates.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.SH SUBCOMMANDS
.TP
key\-generate(1)
Generates a new key
.TP
key\-password(1)
Changes password protecting secrets
.TP
key\-userid(1)
Manages User IDs
.TP
key\-extract\-cert(1)
Converts a key to a cert
.TP
key\-adopt(1)
Binds keys from one certificate to another
.TP
key\-attest\-certifications(1)
Attests to third\-party certifications
.SH "SEE ALSO"
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.
.PP
sq(1)
sq\-armor(1)
sq\-autocrypt(1)
sq\-certify(1)
sq\-dearmor(1)
sq\-decrypt(1)
sq\-encrypt(1)
sq\-inspect(1)
sq\-key\-adopt(1)
sq\-key\-attest\-certifications(1)
sq\-key\-extract\-cert(1)
sq\-key\-generate(1)
sq\-key\-password(1)
sq\-key\-userid(1)
sq\-keyring(1)
sq\-keyserver(1)
sq\-packet(1)
sq\-revoke(1)
sq\-sign(1)
sq\-verify(1)
sq\-wkd(1)
