.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH userid 1 "July 2022" "sq 0.26.0" "Sequoia Manual"
.SH NAME
userid \- Manages User IDs
.SH SYNOPSIS
\fBuserid\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Manages User IDs
.PP
Add User IDs to, or strip User IDs from a key.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.SH SUBCOMMANDS
.TP
userid\-add(1)
Adds a User ID
.TP
userid\-strip(1)
Strips a User ID
.SH "SEE ALSO"
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.
.PP
sq(1)
sq\-armor(1)
sq\-autocrypt(1)
sq\-certify(1)
sq\-dearmor(1)
sq\-decrypt(1)
sq\-encrypt(1)
sq\-inspect(1)
sq\-key(1)
sq\-key\-adopt(1)
sq\-key\-attest\-certifications(1)
sq\-key\-extract\-cert(1)
sq\-key\-generate(1)
sq\-key\-password(1)
sq\-key\-userid\-add(1)
sq\-key\-userid\-strip(1)
sq\-keyring(1)
sq\-keyserver(1)
sq\-packet(1)
sq\-revoke(1)
sq\-sign(1)
sq\-verify(1)
sq\-wkd(1)
