.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH sign 1 "July 2022" "sq 0.26.0" "Sequoia Manual"
.SH NAME
sign \- Signs messages or data files
.SH SYNOPSIS
\fBsign\fR [\fB\-o\fR|\fB\-\-output\fR] [\fB\-B\fR|\fB\-\-binary\fR] [\fB\-\-private\-key\-store\fR] [\fB\-\-detached\fR] [\fB\-\-cleartext\-signature\fR] [\fB\-a\fR|\fB\-\-append\fR] [\fB\-n\fR|\fB\-\-notarize\fR] [\fB\-\-merge\fR] [\fB\-\-signer\-key\fR] [\fB\-t\fR|\fB\-\-time\fR] [\fB\-\-notation\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIFILE\fR] 
.SH DESCRIPTION
Signs messages or data files
.PP
Creates signed messages or detached signatures.  Detached signatures
are often used to sign software packages.
.PP
The converse operation is "sq verify".
.SH OPTIONS
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Writes to FILE or stdout if omitted
.TP
\fB\-B\fR, \fB\-\-binary\fR
Emits binary data
.TP
\fB\-\-private\-key\-store\fR=\fIKEY_STORE\fR
Provides parameters for private key store
.TP
\fB\-\-detached\fR
Creates a detached signature
.TP
\fB\-\-cleartext\-signature\fR
Creates a cleartext signature
.TP
\fB\-a\fR, \fB\-\-append\fR
Appends a signature to existing signature
.TP
\fB\-n\fR, \fB\-\-notarize\fR
Signs a message and all existing signatures
.TP
\fB\-\-merge\fR=\fISIGNED\-MESSAGE\fR
Merges signatures from the input and SIGNED\-MESSAGE
.TP
\fB\-\-signer\-key\fR=\fIKEY\fR
Signs using KEY
.TP
\fB\-t\fR, \fB\-\-time\fR=\fITIME\fR
Chooses keys valid at the specified time and sets the signature\*(Aqs creation time
.TP
\fB\-\-notation\fR=\fINAME VALUE\fR
Adds a notation to the certification.  A user\-defined notation\*(Aqs name must be of the form "name@a.domain.you.control.org". If the notation\*(Aqs name starts with a !, then the notation is marked as being critical.  If a consumer of a signature doesn\*(Aqt understand a critical notation, then it will ignore the signature.  The notation is marked as being human readable.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
[\fIFILE\fR]
Reads from FILE or stdin if omitted
.SH EXAMPLES
 Create a signed message
.PP
.nf
.RS
 sq sign \-\-signer\-key juliet.pgp message.txt
.RE
.fi
.PP
 Create a detached signature
.PP
.nf
.RS
 sq sign \-\-detached \-\-signer\-key juliet.pgp message.txt
.RE
.fi
.SH "SEE ALSO"
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.
.PP
sq(1)
sq\-armor(1)
sq\-autocrypt(1)
sq\-certify(1)
sq\-dearmor(1)
sq\-decrypt(1)
sq\-encrypt(1)
sq\-inspect(1)
sq\-key(1)
sq\-keyring(1)
sq\-keyserver(1)
sq\-packet(1)
sq\-revoke(1)
sq\-verify(1)
sq\-wkd(1)
